input.onButtonPressed(Button.A, function () {
    music.play(music.stringPlayable("C5 B A G F E D C ", 140), music.PlaybackMode.InBackground)
    basic.showIcon(IconNames.Heart)
    basic.showIcon(IconNames.Happy)
    basic.showIcon(IconNames.Heart)
    basic.showIcon(IconNames.Happy)
    basic.showIcon(IconNames.Heart)
    basic.showIcon(IconNames.Happy)
    basic.showIcon(IconNames.Heart)
})
